[package]
name = "git_cli"
version = "0.1.0"
authors = ["Artem <swift.uix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rust-crypto = "^0.2"
regex = "1"
lazy_static = "1.4.0"
